import tubeWatch from '../assets/catalog/watch1.png'
import avondale from '../assets/catalog/watch2.png'
import diver1 from '../assets/catalog/watch3.png'
import diver2 from '../assets/catalog/watch4.png'
import taman from '../assets/catalog/watch5.png'
import malawi from '../assets/catalog/watch6.png'
import diver3 from '../assets/catalog/watch7.png'
import greenlane from '../assets/catalog/watch8.png'
import squardrc from '../assets/catalog/watch9.png'
import diver4 from '../assets/catalog/watch10.png'
import citizen from '../assets/catalog/watch11.png'
import armani from '../assets/catalog/watch12.png'

export const watchDb = [
    {
        id: 0,
        img: tubeWatch,
        title: 'Tube Watch S42 Date Steel With Black Case',
        price: 395,
        description: 'Richly detailed with an understated design - the Police Men’s Greenlane watch.',
        gender: 'Man',
        size: '46x54.5mm',
        caseColour: 'Steel',
        bandMaterial: 'Metal',
        caseMaterial: 'Metal',
        features: 'Multifunction',
        waterResistant: '5 (ATM)',
        bandColour: 'Steel',
    },
    {
        id: 1,
        img: avondale,
        title: 'Avondale Watch Police For Men',
        price: 800,
        description: 'Richly detailed with an understated design - the Police Men’s Greenlane watch.',
        gender: 'Man',
        size: '46x54.5mm',
        caseColour: 'Steel',
        bandMaterial: 'Metal',
        caseMaterial: 'Metal',
        features: 'Multifunction',
        waterResistant: '5 (ATM)',
        bandColour: 'Steel',
    },
    {
        id: 2,
        img: diver1,
        title: 'Diver  300M Co‑Axial Master Chronometer Chronograph',
        price: 600,
        description: 'Richly detailed with an understated design - the Police Men’s Greenlane watch.',
        gender: 'Man',
        size: '46x54.5mm',
        caseColour: 'Steel',
        bandMaterial: 'Metal',
        caseMaterial: 'Metal',
        features: 'Multifunction',
        waterResistant: '5 (ATM)',
        bandColour: 'Steel',
    },
    {
        id: 3,
        img: diver2,
        title: 'Diver 300M Co-Axial Master Chronometer',
        price: 1400,
        description: 'Richly detailed with an understated design - the Police Men’s Greenlane watch.',
        gender: 'Man',
        size: '46x54.5mm',
        caseColour: 'Steel',
        bandMaterial: 'Metal',
        caseMaterial: 'Metal',
        features: 'Multifunction',
        waterResistant: '5 (ATM)',
        bandColour: 'Steel',
    },
    {
        id: 4,
        img: taman,
        title: 'Taman Watch By Police For Men',
        price: 500,
        description: 'Richly detailed with an understated design - the Police Men’s Greenlane watch.',
        gender: 'Man',
        size: '46x54.5mm',
        caseColour: 'Steel',
        bandMaterial: 'Metal',
        caseMaterial: 'Metal',
        features: 'Multifunction',
        waterResistant: '5 (ATM)',
        bandColour: 'Steel',
    },
    {
        id: 5,
        img: malawi,
        title: 'Malawi Watch Police For Men',
        price: 555,
        description: 'Richly detailed with an understated design - the Police Men’s Greenlane watch.',
        gender: 'Man',
        size: '46x54.5mm',
        caseColour: 'Steel',
        bandMaterial: 'Metal',
        caseMaterial: 'Metal',
        features: 'Multifunction',
        waterResistant: '5 (ATM)',
        bandColour: 'Steel',
    },
    {
        id: 6,
        img: diver3,
        title: 'Diver 300M Co-Axial Master Chronometer ',
        price: 1200,
        description: 'Richly detailed with an understated design - the Police Men’s Greenlane watch.',
        gender: 'Man',
        size: '46x54.5mm',
        caseColour: 'Steel',
        bandMaterial: 'Metal',
        caseMaterial: 'Metal',
        features: 'Multifunction',
        waterResistant: '5 (ATM)',
        bandColour: 'Steel',
    },
    {
        id: 7,
        img: greenlane,
        title: 'Greenlane Watch By Police For Men',
        price: 1000,
        description: 'Richly detailed with an understated design - the Police Men’s Greenlane watch.',
        gender: 'Man',
        size: '46x54.5mm',
        caseColour: 'Steel',
        bandMaterial: 'Metal',
        caseMaterial: 'Metal',
        features: 'Multifunction',
        waterResistant: '5 (ATM)',
        bandColour: 'Steel',
    },
    {
        id: 8,
        img: squardrc,
        title: 'Squardrc 5402 Chrono',
        price: 359,
        description: 'Richly detailed with an understated design - the Police Men’s Greenlane watch.',
        gender: 'Man',
        size: '46x54.5mm',
        caseColour: 'Steel',
        bandMaterial: 'Metal',
        caseMaterial: 'Metal',
        features: 'Multifunction',
        waterResistant: '5 (ATM)',
        bandColour: 'Steel',
    },
    {
        id: 9,
        img: diver4,
        title: 'Diver  300M Co‑Axial Master Chronometer Chronograph',
        price: 400,
        description: 'Richly detailed with an understated design - the Police Men’s Greenlane watch.',
        gender: 'Man',
        size: '46x54.5mm',
        caseColour: 'Steel',
        bandMaterial: 'Metal',
        caseMaterial: 'Metal',
        features: 'Multifunction',
        waterResistant: '5 (ATM)',
        bandColour: 'Steel',
    },
    {
        id: 10,
        img: citizen,
        title: 'Citizen',
        price: 519,
        description: 'Richly detailed with an understated design - the Police Men’s Greenlane watch.',
        gender: 'Man',
        size: '46x54.5mm',
        caseColour: 'Steel',
        bandMaterial: 'Metal',
        caseMaterial: 'Metal',
        features: 'Multifunction',
        waterResistant: '5 (ATM)',
        bandColour: 'Steel',
    },
    {
        id: 11,
        img: armani,
        title: 'Armani Exchange',
        price: 400,
        description: 'Richly detailed with an understated design - the Police Men’s Greenlane watch.',
        gender: 'Man',
        size: '46x54.5mm',
        caseColour: 'Steel',
        bandMaterial: 'Metal',
        caseMaterial: 'Metal',
        features: 'Multifunction',
        waterResistant: '5 (ATM)',
        bandColour: 'Steel',
    },
]